fix linter warnings
BTW, these warnings do not show up locally for me, only in CI. Maybe
divergent version of clj-kondo?

::info file=src/fluree/db/api.cljc,line=27,col=29::Unused excluded var: merge
::info file=src/fluree/db/connection.cljc,line=2,col=29::Unused excluded var: replicate
::info file=src/fluree/db/flake.cljc,line=2,col=29::Unused excluded var: partition-by
::info file=src/fluree/db/flake.cljc,line=2,col=42::Unused excluded var: remove
::info file=src/fluree/db/flake.cljc,line=2,col=49::Unused excluded var: split-at
::info file=src/fluree/db/flake.cljc,line=2,col=86::Unused excluded var: take
::info file=src/fluree/db/flake/flake_db.cljc,line=2,col=34::Unused excluded var: vswap!
::info file=src/fluree/db/json_ld/iri.cljc,line=88,col=41::Redundant int coercion - expression already has type int
::info file=src/fluree/db/method/ipfs/keys.cljc,line=5,col=34::Unused excluded var: key
Error: Unresolved symbol: form#
::info file=src/fluree/db/query/fql.cljc,line=14,col=29::Unused excluded var: var?
::info file=src/fluree/db/query/fql.cljc,line=14,col=34::Unused excluded var: vswap!
::info file=src/fluree/db/storage.cljc,line=2,col=34::Unused excluded var: list
::info file=src/fluree/db/storage/localstorage.cljs,line=2,col=29::Unresolved excluded var: read
::info file=src/fluree/db/storage/localstorage.cljs,line=2,col=34::Unused excluded var: list
::info file=src/fluree/db/storage/s3.clj,line=2,col=29::Unused excluded var: read
::info file=src/fluree/db/storage/s3.clj,line=2,col=34::Unused excluded var: list
::info file=src/fluree/db/virtual_graph/bm25/index.clj,line=17,col=29::Unused excluded var: assert
::info file=test/fluree/db/util/json_test.cljc,line=39,col=28::Redundant double coercion - expression already has type double
::info file=test/fluree/db/util/json_test.cljc,line=88,col=28::Redundant double coercion - expression already has type double
::info file=test/fluree/db/util/json_test.cljc,line=137,col=28::Redundant double coercion - expression already has type double
::info file=test/fluree/db/util/json_test.cljc,line=188,col=28::Redundant double coercion - expression already has type double
::info file=test/fluree/db/util/json_test.cljc,line=237,col=28::Redundant double coercion - expression already has type double
::info file=test/fluree/db/util/json_test.cljc,line=286,col=28::Redundant double coercion - expression already has type double
linting took 5527ms, errors: 1, warnings: 0